### PR TITLE
feat: 🎸 Make 5.2.0 version as default version

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

Sets `fiveTwoZeroConfig` as  the default config. Also, updates the compatible service versions for 5.2.0 config

### Breaking Changes

NA

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by prashantasdeveloper** [comment]
This should be merged only when 5.2.0 image for mainnet is available in [docker hub](https://hub.docker.com/r/polymeshassociation/polymesh/tags).

**Comment by polymath-eric** [comment]
I am not sure, but it might be version v5.2.1 upstream when mainnet branch gets updated. I think a patch got version got added.

**Review by polymath-eric — APPROVED** [review]
LGTM

**Review by VictorVicente — APPROVED** [review]

**Review by polymath-eric — APPROVED** [review]

**Pull request merged**
